### ISSUE TITLE
Titles are duplicated when extending role assignments

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#1735] opened 2022-10-24 12:32 UTC
Reproduce:
1. Extend a role assignment
2. Check title

Expected behaviour:
Title should be "Strategic Anchor Council"

Experienced behaviour:
Title is duplicated: "Strategic Anchor Council: Strategic Anchor Council"

e.g. https://dao.hypha.earth/hypha/proposals/37101
e.g. https://dao.hypha.earth/hypha/proposals/

<img width="649" alt="image" src="https://user-images.githubusercontent.com/75991832/197526095-bb3e9e4a-8351-488b-88eb-17fbd33b41f8.png">

<img width="961" alt="image" src="https://user-images.githubusercontent.com/75991832/197526119-be02f673-fce5-4160-86a2-c63bf1da0aa6.png">

**Comment by evgenibir** [comment] 2022-11-05 07:35
Hello @leonieherma1! It seems to me that this is not a bug, I checked the current list of proposals and could not find something similar. Also, there is no symbol in the code: in the title, only what was entered when creating the proposal is transmitted there. I think this was put into the title when it was created.

**Comment by leonieherma1** [comment] 2022-11-05 19:42
Hm I will check the issue again when I extend my assignment next week on dev

**Comment by evgenibir** [comment] 2022-12-09 07:50
@leonieherma1 I dug into the code and found a place where this happens, and I don't know if it's a bug or a feature :) . In general, this is not a duplicate of the same title, but a little different. The first part before ":" is the name of the original proposal, the one that is being extended, and after the ":" is the title of the current proposal. This is only about the type Extension, for other types it is not. I can remove it if necessary, I don't really know who did it or why, but it clearly made some sense.

**Comment by leonieherma1** [comment] 2022-12-09 17:09
@evgenibir let's just keep the original title and remove "title of current proposal". In the proposal creation wizard the title should not be editable.
Makes sense?

**Comment by evgenibir** [comment] 2022-12-12 08:12
> @evgenibir let's just keep the original title and remove "title of current proposal". In the proposal creation wizard the title should not be editable. Makes sense?

Hi @leonieherma1, sure, i`ll do it

**Closed** 2022-12-16 19:03 UTC
Labels: Bug
