### ISSUE TITLE
[R] Add [Abstain] to vote

### ISSUE THREAD

**Issue by sceenius** [hypha-dao/dho-web-client#72] opened 2020-09-10 14:07 UTC
1 Add vote button [Abstain]
2 Rename [Enroll] and [Endorse] to [Yes]
3 Rename [Reject] to [No]

Should  [Abstain] be counted in pass / fail (unity) ?
Yes: because it diffuses the Yes/No votes (better power balance)
No: because it dilutes the arguments (unclear outcomes)
Abstain: (1) you don't really care but need to increase the quorum, (2) you understand the vote but signal you are not taking sides

## Example
Note: the following example is for majority vote and 1H1V, Hypha does not have this situation and this is to explain the border case, which still applies (the yes/no boxes have different sizes based on HVOICE and the majority is 80% or some other number).
  
You’re on a board of 12, all of whom are present, and 10 people vote and two abstain, do you need six yes votes to win or seven? 6 if you do not count abstentions, 7 if you do. More details on this case [here](
https://www.lawoforderblog.com/2018/03/4-things-most-people-get-wrong-about-abstentions/)

![DHO ABSTAIN (2)](https://user-images.githubusercontent.com/24725582/93260686-b945a080-f76f-11ea-8c04-6fad5f5d9107.png)

:warning: Pay attention to what is the min and max required to pass? That's the ground for manipulative voting schemas
:warning: Pay attention to too many Abstentions - something not right and smaller group has larger decision power

**Comment by n13** [comment] 2020-09-10 14:28
6 votes to win in this case. Otherwise abstain would be sort of like a no?!

The problem is more that if 8 abstain and 1 votes no, this 1 can kill the deal when 80% majority is needed.

**Comment by sceenius** [comment] 2020-09-10 14:36
Yes, but I think that is more voter apathy and points to a different problem you have ;)

**Comment by sceenius** [comment] 2020-09-10 16:11
We will socialize this more before adding to the next release.

**Comment by dappdever** [comment] 2020-09-24 13:06
@sceenius I'm going to parrot back the rules here to ensure that I understand them.  

- Currently, the voting options are pass/fail.  I will be adding a 3rd option: "abstain".
- All 3 options will be included in the quorum quantity, which is (passing+failing+abstain)/total HVOICE.  The quorum requirement remains as greater than or equal to 20% of the total supply of HVOICE.
- In order for proposal to pass, there still needs be 80% passing vote as calculated by (passing votes)/(passing votes+failing votes).  Note that the abstain votes are not included in the denominator.  
- Put another way (and this is how the code works), proposals need a passing vote quantity that is greater than 4x the failing vote quantity (independent of abstain).  The 4x comparative calculation ensures it is over 80%.

**Comment by sceenius** [comment] 2020-09-24 13:41
Perfect.

**Comment by dappdever** [comment] 2020-09-24 14:05
@gregory-latinier - this has been deployed to the testnet. You can add this to the UI voting screen and we can deploy to prod at the same time when ready.

**Closed** 2020-09-29 09:58 UTC
